
[colors]
draw_bold_text_with_bright_colors = true

[cursor]
# vi_mode_style = "None"

[cursor.style]
blinking = "Always"
shape = "Underline"

[font]
builtin_box_drawing = true
size = 14.0

[font.bold]
family = "FiraCode Nerd Font"
style = "Bold"

[font.bold_italic]
family = "FiraCode Nerd Font"
style = "Bold Italic"

[font.italic]
family = "FiraCode Nerd Font"
style = "Italic"

[font.normal]
family = "FiraCode Nerd Font"
style = "Regular"

[font.offset]
x = 0
y = 5 

[scrolling]
history = 10000
multiplier = 3

[terminal.shell]
args = ["-l", "-c", "tmux a -t 0 || tmux"]
program = "/bin/zsh"

[window]
decorations = "Full"
decorations_theme_variant = "None"
dynamic_title = false
dynamic_padding = true
opacity = 0.85
startup_mode = "Windowed"
blur = true

[window.padding]
x = 4
y = 8

[general]
import = ["/Users/kazuto/.config/alacritty/themes/remedy_dark.toml"]
